%% PLAY_AUDIO_DEMO
% Simple listening test: clean vs noisy vs three denoisers.

clc;

files = { ...
    'results/original.wav', ...
    'results/noisy.wav', ...
    'results/wiener_denoised.wav', ...
    'results/spectral_denoised.wav', ...
    'results/hybrid_denoised.wav' ...
    };

labels = { ...
    'Clean speech', ...
    'Noisy speech', ...
    'Wiener output', ...
    'Spectral subtraction output', ...
    'Hybrid output' ...
    };

for k = 1:numel(files)
    f = files{k};
    if ~exist(f, 'file')
        warning('File not found: %s (skipping)', f);
        continue;
    end

    [x, fs] = audioread(f);
    fprintf('\nPlaying: %s\n', labels{k});
    soundsc(x, fs);
    pause(min(8, length(x)/fs) + 1);   % 播 8 秒左右，然后停一下
end

fprintf('\nDone.\n');
